dashevo/js-dash-sdk

.gitignore, README.md, examples/node/usage.es5.js, examples/ts/usage.es6.ts, examples/usage.es6.ts, examples/web/schema.js, examples/web/usage.web.html, examples/web/usage.web.js, package-lock.json, package.json, src/DashJS/SDK/Platform/Platform.ts, src/DashJS/SDK/Platform/methods/documents/fetch.ts, src/DashJS/SDK/SDK.spec.ts, src/DashJS/SDK/SDK.ts, tsconfig.json, webpack.config.js
Since the precedent change over the API : 
- Building procedure is failing and scripts needs updates.
- Package is having some issues (syntax, deps).
- Unit Test are missing.
- Usage need improvements
- Fixed usage files 
- Fixed webpack building for node
- Added webpack building for web 
Documentation has been updated, conflict will happen when merging #3.
=> Fix: Issue on usage + interface impr

.npmignore, .travis.yml, scripts/travis-deploy.sh, src/DashJS/SDK/SDK.spec.ts, tests/e2e/index.js
We want travis to perform some work for us such as our unit tests and deploy to npm on a branch being merged.
- Added .travis.yml config which will call travis-deploy.sh
- Added travis.deploy to deploy to npm on merge
We actually already use this in our other repo (wallet-lib). 
Live test with travis will happen on our next PR.
=> chore: added travis deployment script

docs/usage/dapi.md
Info at https://dashevo.github.io/DashJS/#/usage/dapi was out of date.
Replaced incorrect info with correct info
=> doc: fix outdated info on accessing DAPI client

src/DashJS/SDK/Platform/Platform.ts, src/DashJS/SDK/Platform/methods/contracts/broadcast.ts, src/DashJS/SDK/Platform/methods/contracts/create.ts, src/DashJS/SDK/Platform/methods/contracts/get.ts, src/DashJS/SDK/Platform/methods/documents/broadcast.ts, src/DashJS/SDK/Platform/methods/documents/create.ts, src/DashJS/SDK/Platform/methods/documents/get.ts, src/DashJS/SDK/Platform/methods/identities/get.ts, src/DashJS/SDK/Platform/methods/identities/register.ts, src/DashJS/SDK/Platform/methods/names/get.ts, src/DashJS/SDK/Platform/methods/names/register.ts, src/DashJS/SDK/SDK.ts, src/DashJS/SDK/methods/isReady.ts, typings/dapi-client.d.ts
Tell me if I nailed it 😃 
This PR brings Typescript documentation which allows Intellisense in modern IDE.
This PR shall deprecate {contract, document}.broadcast.
Some repetive found code was simplified.
Implemented ts-doc and cleaning
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.
=> TypeScript Documentation & some code cleaning

docs/examples/use-local-evonet.md, docs/getting-started/multiple-apps.md, docs/platform/contracts/get.md, examples/node/retrieve-contract.js, src/DashJS/SDK/SDK.ts, tests/z_integrations/user-flow-1.js
DPNS contract ID changed so some functionality returns errors
Updated DPNS contract ID
=> fix: change DPNS contract ID to match redeployed evonet

docs/platform/about-platform.md
Please include a summary of what is the issue being fixed, along with the relevant motivation and context.
List any dependencies that are required for this change.
Please include a summary of the change
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.
=> Fix dead link in docs

README.md
Plus, it rhymes now!
See title
- [ NA ] My code follows the style guidelines of this project
- [ NA ] I have performed a self-review of my own code
- [ NA ] I have commented my code, particularly in hard-to-understand areas
- [ NA ] I have made corresponding changes to the documentation
=> doc: remove duplicate link + slight wording change

examples/node/register-contract.js
@Alex-Werner Did not push directly to develop in case you were making changes also
Missing contract registration example
Added example
=> doc: add example contract register

CHANGELOG.md, package-lock.json, package.json
Updated changelog for the most recent changes
Updated changelog, bump patch version
Nothig to test
=> chore: bump patch version to 3.0.2 and update CHANGELOG.md

src/SDK/Client/Client.ts, tests/functional/index.js, tests/z_integrations/user-flow-1.js
In order to allow users to connect to the new endpoint and to resolve some accessibility issue to the seeds from outside, we bring this PR
- fix: replaced DNS seeds (seed-1, ..., seed-5.evonet.networks...).
- fix: updated DPNS contractID
Successful integration tests means a proper resolving on those seeds. 
Also manual testing.
=> fix: evonet redeploy

tests/functional/sdk.js
the SDK functional test are failing from time to time
- Use random inputs for funding transaction
- Add some delay before data contract fetching
Has been running tests many times.
None
=> test: use random inputs for wallet funding in sdk test

CHANGELOG.md, package-lock.json, package.json
This PR update wallet-lib to 7.13.2 which brings multiples fixes and an additional features. 
Especially it adds fix for identity listing and therefore fix a usage issue on registering documents.
As well as an initial sync up fix so we do ensure to sync ALL addresses immediately before releasing (which in the previous build were done later during the app execution). 
- chore: update wallet-lib to 7.13.2
=> chore(release): v3.13.3

src/SDK/Client/Platform/createAssetLockTransaction.ts, src/SDK/Client/Platform/methods/identities/register.ts
Minor formatting fix to remove 2 LGTM alerts
Insert missing semicolons
N/A
N/A
=> chore: add missing semicolons to fix LGTM 2 alerts

README.md
Brings readme into [standard-readme](https://github.com/RichardLitt/standard-readme) compliance
N/A
N/A
=> docs: update for standard-readme compliance

package-lock.json, package.json
There are some bugs and previous versions of Wallet and DashCore libs
Update Wallet lib to 7.13.4 and DashCore lib to 0.18.11
With unit and functional tests
None
=> feat: update Wallet and DashCore libs

src/SDK/Client/Platform/methods/names/register.ts
Remove unused variable (and check if LGTM working :slightly_smiling_face:)
Removed extraneous line
N/A
=> chore: remove unused variable

package-lock.json, package.json
Updating version before pre-release
Updated version to `3.14.0-dev.3`
Tests.
None.
=> chore: bump version to 3.14.0-dev.3

package-lock.json, package.json, src/SDK/Client/Client.ts
Update DAPI Client to v0.14.0-dev.8
* Updated DAPI Client
* Updated DAPIClientOptions definition
Unit tests
The DAPI Client option `addresses` renamed to `dapiAddresses`
=> feat!: update DAPI Client to v0.14.0-dev.8

package-lock.json, package.json
Need to update DPP to new version
DPP updated to 0.14.0-dev.4
Unit tests
=> feat: update DPP to 0.14.0-dev.4

package-lock.json, package.json
To make a pre-release we need to bump version.
Version bumped to 3.14.0-dev.4
Unit tests
None
=> chore: bump version to 3.14.0-dev.4

CHANGELOG.md, package-lock.json, package.json
Release 3.14.0
Updated changelog and bumped package version to 3.14.0
With tests.
None
=> chore(release): update changelog and bump version to 3.14.0

src/SDK/Client/Client.ts
Outdated DPNS Contract ID hardcoded as default option in Client.
Updated to a new one.
None
None
=> fix: outdated DPNS contract ID

package-lock.json, package.json
Need to update dapi-client
dapi-client was updated to 0.15.0-dev.1
Unit tests
None
=> feat: update dapi-client to 0.15.0-dev.1

package-lock.json, package.json
Need to update wallet-lib
wallet-lib was updated to 7.15.0-dev.1
Unit tests
None
=> feat: update wallet-lib to 7.15.0-dev.1

docs/platform/names/register.md, docs/platform/names/resolveByRecord.md, package-lock.json, package.json, src/SDK/Client/Platform/methods/names/register.spec.ts, src/SDK/Client/Platform/methods/names/register.ts, src/SDK/Client/Platform/methods/names/resolve.spec.ts, src/SDK/Client/Platform/methods/names/resolve.ts, src/SDK/Client/Platform/methods/names/resolveByRecord.spec.ts, src/SDK/Client/Platform/methods/names/resolveByRecord.ts, tests/fixtures/contracts.json
Updating `DPNS` methods to use new `DPNS` contract
- Updated `register` and `resolve` methods
Unit tests.
`client.platform.names.register` now receive records as a second argument.
=> feat!: update to new Wallet and DPNS contract

package-lock.json, package.json
Updated version
Updated version
=> chore: bump version to 3.15.0-dev.2

.travis.yml
We've changed repo name for some reason
Update it in Travis config
=> fix: repo name in Travis config was invalid

package-lock.json, package.json
Updated version
Updated version
=> chore: bump version to 3.15.0-dev.3

CHANGELOG.md, package-lock.json, package.json, src/SDK/Client/Client.ts
Release 0.15
Changelog updated and version bumped to 0.15.0
None
None
=> chore(release): update changelog and bump version to 0.15

package-lock.json
```
TypeError: Invalid argument type: script
at Output.push../node_modules/@dashevo/wallet-lib/node_modules/@dashevo/dashcore-lib/lib/transaction/output.js.Output.setScript
```
The package-lock file is recreated.
With tests
None
=> fix: invalid argument type: script error from dashcore-lib

package-lock.json, package.json
To make a new pre-release we need to bump version
Bumped version
Unit tests
None
=> chore: bump version to 3.17.0-dev.1

package-lock.json, package.json
To make a new pre-release we need to bump version
Bumped version
Unit tests
None
=> chore: bump version to 3.17.0-dev.2

docs/README.md, docs/getting-started/about-schemas.md, docs/getting-started/core-concepts.md, docs/getting-started/dash-platform-applications.md, docs/getting-started/multiple-apps.md, docs/getting-started/quickstart.md, docs/index.html
https://dashevo.github.io/js-dash-sdk/ has not kept up with changes. 
This PR focuses just on the Readme and some parts of the Getting Started section. More updates will be necessary for other sections, but are not the scope of this PR. Updates are made to the master branch because it's the branch that builds the live site which people access.
Being built on my fork of the repo: https://thephez.github.io/DashJS/
N/A
=> docs: update several out of date docs in getting started section

src/SDK/Client/ClientApps.spec.ts, src/SDK/Client/Platform/methods/contracts/get.spec.ts, src/SDK/Client/Platform/methods/contracts/get.ts
Issue #150
Cache contract in all client apps with the corresponding contract ID
With unit tests
None
=> fix: cannot read property 'getBinaryProperties' of undefined

CHANGELOG.md, package-lock.json, package.json
Release 3.16.2
- Updated changelog
- Bumped version to 3.16.2
None
None
=> chore(release): update changelog and bump version to 3.16.2

package-lock.json, package.json
Updates to latest release of dashcore-lib which fixes a bug described here:
https://github.com/dashevo/dashcore-lib/pull/197
update dashcore-lib dependency
bumped version
Travis, unit tests
ran it in Dash Chrome Wallet
=> chore: update dashcore-lib dependency

.travis.yml, src/SDK/Client/Platform/methods/contracts/broadcast.ts, src/SDK/Client/Platform/methods/documents/broadcast.ts, src/SDK/Client/Platform/methods/identities/register.ts
The current ack mechanism ensures only that data is committed and does not wait until the next block will be committed and data become available in DAPI (https://github.com/dashevo/js-drive/pull/429).
wait broadcasted data to be available from queries
With mn-bootstrap
=> feat: wait broadcasted data to be available from queries

package-lock.json, package.json
To make a new pre-release we need to bump version
Bumped version
Unit tests
None
=> feat: bump version to 3.17.0-dev.3

package-lock.json, package.json, src/SDK/Client/Client.spec.ts, src/SDK/Client/Client.ts, src/SDK/Client/Platform/Platform.ts, src/SDK/Client/Platform/createAssetLockTransaction.ts, src/SDK/Client/Platform/methods/documents/broadcast.ts, src/SDK/Client/Platform/methods/identities/register.ts, src/SDK/Client/Platform/methods/identities/topUp.ts, src/test/mocks/createDapiClientMock.ts, src/utils/createFakeIntantLock.ts
Asset lock proofs for identity funding
- updated dpp and dashcore-lib
- used `account.waitForInstantLock` method in the `identities.register` method
- used `account.waitForInstantLock` method in the `identities.topUp` method
- added fallback for regtest tests to pass fake is lock instead of waiting for a real one
- added `passFakeAssetLockProofForTests` option to the `Client` constructor
- added `checkAssetLockTransactionOutPointExists` to the state repository that always returns `false`, as we don't need to check it on the client side
Added integration test with a transport and dapi client mocks
Requires a version of DAPI with instant locks implemented, i.e. 0.17-dev.3 or higher
=> feat!: asset lock proofs for identity funding

package-lock.json, package.json
=> chore(release): dash-js-sdk v3.17.0-dev.4

src/SDK/Client/Platform/methods/names/register.spec.ts
`crypto.randomBytes` stub causing other tests to fail
Add proper stub restoring in the test it used
Run the tests
None
=> fix: crypto.randomBytes stub causing tests to fail

package-lock.json, package.json
update `dapi-client`, `dashcore-lib`, `dpp` and `wallet-lib`
update `dapi-client`, `dashcore-lib`, `dpp` and `wallet-lib`
=> feat: update `dapi-client`, `dashcore-lib`, `dpp` and `wallet-lib`

package-lock.json, package.json
bump version to 3.17.0-dev.5
bump version to 3.17.0-dev.5
=> chore: bump version to 3.17.0-dev.5

docs/getting-started/core-concepts.md, package-lock.json, package.json, src/SDK/Client/Client.spec.ts, src/SDK/Client/Client.ts
Connect to testnet by default
Set default network option to testnet
With tests
Connect to testnet by default
=> feat!: connect to testnet by default

package-lock.json, package.json, src/SDK/Client/Client.ts
Updating latest testnet DPNS contract + some deps
- DPNS contract id
- `dapi-client` and `wallet-lib` updated
None.
None.
=> feat: update DPNS contract id and some dependecies

package-lock.json, package.json
=> chore: bump version to 3.18.0-dev.1

package-lock.json, package.json
To make a new pre-release we need to bump version
Bumped version
Unit tests
None
=> chore: bump version to 3.18.0-dev.2

src/SDK/Client/Platform/methods/names/search.ts
Fixes #182. Perhaps should be backported to v17 also.
Created a normalized version of the labelPrefix to use in the query so mixed-case label prefix arguments don't mysteriously fail.
N/A
=> fix: ensure name search uses lowercase label

.travis.yml, package-lock.json, package.json, src/SDK/Client/Client.spec.ts, src/SDK/Client/Client.ts, src/SDK/Client/Platform/methods/identities/internal/createIdentityCreateTransition.ts, src/SDK/Client/Platform/signStateTransition.ts, src/test/fixtures/createIdentityFixtureInAccount.ts, tests/functional/sdk.js
Updated wallet-lib to a version with hardened derivation paths
Update wallet-lib and its usages
Run the test suite
- Identities registered in versions prior to that one won't sync, as identities are now using hardened derivation and derived from the wallet, not from the account. This change is made to make JS SDK compatible with Android and iOS apps and DIP 11.
=> feat!: make identity derivation DIP-11 compatible

package-lock.json, package.json
=> chore: bump version to 3.18.0-dev.3

package-lock.json, package.json
=> chore: update all dependencies to released versions

CHANGELOG.md, package-lock.json, package.json
Release 0.18.0
- Update changelog
- Bump version to 0.18.0
None
None
=> chore(release): update changelog and bump version 0.18.0

package.json, src/SDK/Client/Client.ts
To properly catch Wallet errors, they have to be propagated using Client as an event emitter
- Client now an Event Emitter
- Wallet errors propagated using `error` event of a `Client` class
Test suite
None
=> feat: handle wallet async errors

.travis.yml, package-lock.json, package.json
Bump version
Bump version
Local setup
None.
=> chore: bump version to 3.19.0-dev.1

package.json, src/SDK/Client/Client.ts, src/SDK/Client/Platform/Platform.ts, src/SDK/Client/Platform/methods/identities/internal/createAssetLockProof.ts
Removed fake instant locks proofs since mn-bootstrap can produce normal proofs in CI now
Remove fallback and fallback options
Run the unit test
Remove 'passFakeInstantLocksForTest' option from the client constrcutor
=>  feat: remove fake instant locks proofs

package-lock.json, package.json
Bumped version to 3.19.0-dev.2
No
=> chore: bump version to 3.19.0-dev.2

package-lock.json, package.json
Update wallet lib to 0.18.1 that is a bugfix release
=> chore: update wallet-lib to 0.18.1

CHANGELOG.md, package-lock.json, package.json
=> chore(release): js-dash-sdk v0.18.2

CHANGELOG.md, package-lock.json, package.json
=> chore(release): Dash SDK v3.19.3

package-lock.json, package.json
Error when serializing fields that are supposed to be binaries in the dapi-client
Update dapi-client and wallet-lib to a version with a fix
Run the tests
None
=> fix: query serialization with binary fields

CHANGELOG.md, package-lock.json, package.json
=> chore(release): Dash SDK v3.19.4

package-lock.json, package.json
Version bumped to 3.20.0-dev.2
No
=> chore: bump version to 3.20.0-dev.2

.github/workflows/.env, package-lock.json, package.json, src/SDK/Client/Client.ts, tests/functional/sdk.js
We need to pass waitForInstantLockTimeout option to wallet
- Update wallet options
- Move walletAccountIndex to wallet options
Use `wallet.defaultAccountIndex` instead of `walletAccountIndex` option.
=> feat!: update wallet options

package-lock.json, package.json
The version bumped to 3.20.0-dev.3
No
=> chore(release): bump version to 3.20.0-dev.3

.github/workflows/test_and_release.yml
CI was failing with `[FAILED] Docker Compose V2 is not installed` due to an update in `gh-action-start-local-network`
- Add compose v2 installation step
- Delete unused variables
in CI
=> chore(ci): satisfy new compose v2 dependency

.github/workflows/test_and_release.yml
If branches are specified, dashmate will build them, slowing down CI. The satackey cache action does not give appreciable benefits in this case.
- Remove satackey cache action
- Add buildkit caching
In CI
None
=> build: use docker BuildKit cache

package-lock.json, package.json
Need to bump version before release
The version was bumped to 3.20.0-dev.4
With tests
None
=> chore: bump version to 3.20.0-dev.4

.github/workflows/.env, package-lock.json, package.json
=> chore: bump version to 3.21.0-dev.1

package-lock.json, package.json
Version bumped to 3.21.0-dev.2
In CI
None
=> chore: bump version to 3.21.0-dev.2

package-lock.json, package.json
Need to bump version to make a new pre-release
The version was bumped to 3.21.0-dev.3
Unit tests
No
=> chore: bump version to 3.21.0-dev.3

package-lock.json, package.json
grpc-common version was updated
Update grpc-common dep versions
In CI
=> chore: update grpc-common deps

package-lock.json, package.json
Bump version to 3.21.0-dev.4
In CI
None
=> chore: bump version to 3.21.0-dev.4

package-lock.json, package.json
Need to bump version to make a new pre-release
The version was bumped to 3.21.0-dev.5
Unit tests
No
=> chore: bump version to 3.21.0-dev.5

.github/workflows/.env, package-lock.json, package.json, src/SDK/Client/Platform/Platform.spec.ts, src/SDK/Client/Platform/Platform.ts, src/SDK/Client/Platform/methods/contracts/get.spec.ts, src/SDK/Client/Platform/methods/contracts/get.ts, src/SDK/Client/Platform/methods/identities/get.ts
Provide comprehensive  error codes for DAPI responses
- Updated DPP
- Updated DAPI Client
With tests
None
=> feat: comprehensive error codes

package-lock.json, package.json
Need to bump version to make a new pre-release
The version was bumped to 3.21.0-dev.6
Unit tests
No
=> chote: bump version to 3.21.0-dev.6

package-lock.json, package.json
Bump version for release
Bump version to 3.21.0-dev.8
=> chore: bump version to 3.21.0-dev.8

.github/workflows/.env, package-lock.json, package.json
Bump version for release
Bump version to 3.21.0-dev.9
=> chore: bump version to 3.21.0-dev.9

package-lock.json, package.json
Bump version for release
Bump version to 3.21.0-dev.10
=> chore: bump version to 3.21.0-dev.10
