dashevo/js-dash-sdk

.travis.yml

We want travis to perform build + deploy on PR being merged in master.
But we currently have set the wrong repository name (repo value in travis is not supposed to be npm but github repo name).
Make deploy on match repo name

chore: update .travis.yml

---

README.md
docs/README.md
docs/getting-started/quickstart.md
docs/usage/dashcorelib-primitives.md

Several references to @dashevo/dashjs remain in places that should just be "dash"
Updated readme to remove incorrect references
N/A

docs: update @dashevo/dashjs references to dash

---

.travis.yml
scripts/travis-deploy.sh

Node version 8 reaches End-of-Life on 31st December (tomorrow). Both 10 and 12 are Active LTS 'til April 2021.
Also bump latest Node LTS version -- this would affect the deploy, using v12 instead of v10 to deploy. @Alex-Werner let me know if you want to discuss supporting _lowest_ instead of highest Node LTS version. I can also split this into a separate PR if you prefer.

Update Node versions for Travis

---

package-lock.json
package.json
src/DashJS/SDK/Platform/methods/identities/register.ts

When using `platform.identity.register()`, the locktx was being broadcasted, the ST prepared but not broadcasted. 
This resolves that failing process. 
- Call client.applyStateTransition to send our prepare ST to the state machine.  
- Registered `AaGHAQaCNqvJdeJFtVByc8Pa8bTAM1YGKHnG7Sjsh6nq` and fetch-it back worked as intended.
Thanks to @Antti-Kaikkonen for reporting and helping fixing the bug !

fix(Identity): .register was not applying ST

---

.travis.yml
package.json
scripts/travis-deploy.sh

This does several things:
- Install dependencies via `npm ci`
- Add check-package scripts to ensure same values for both name and version in `package.json` and `package-lock.json`
- Set Travis config to only deploy on tags, and only for this repo (not forks, for example)
- Update deploy script to check tags. The first check `$PACKAGE_TAG" != "$TRAVIS_TAG"` makes sure the tag version number pushed via `git` is equal to the version number in `package.json`. It should be "v1.2.3" for example, for the tag, and "1.2.3" in the package.json version.
It also checks if the string "dev" exists in the tag in order to not use "latest" for a dev tag. Then it publishes the module to npm with a tag of either `latest` or `dev`.

chore: Enable tag based deploy pipeline

---

.travis.yml

Based on #18 , will rebase if / when that gets merged. Currently that is running on xenial by default.

chore: Use latest Travis dist bionic

---

docs/_sidebar.md

The documents-related links were going to the contract documents
Fixed links

doc: Fix incorrect docsify links in_sidebar.md

---

src/DashJS/SDK/Platform/Platform.ts
src/DashJS/SDK/Platform/methods/contracts/get.ts
src/DashJS/SDK/Platform/methods/documents/create.ts
src/DashJS/SDK/Platform/methods/documents/get.ts
src/DashJS/SDK/Platform/methods/names/register.ts
src/DashJS/SDK/SDK.ts
tests/z_integrations/user-flow-1.js

If we were to manage multiples apps with an updated dpns (with another order than [0]), creating a new names would have failed to find `domain` and `preorder` from the schema.
- Fix the issue by passing it the expected locator (`dpns.`)
- Impr: error handling on fetching contracts & documents
Using current test suite. 
- [N/A] I have made corresponding changes to the documentation

fix(DPNS): error handling & type locator

---

package.json

@Alex-Werner Not sure this is how you want to handle this, but it appears to work.
Fix for DPNS name registration failure (#26). It appears that a change in js-dpp 0.10.0-dev.15 introduced something incompatible with current Evonet.
Hold dpp at 0.10.0-dev.14 for now in `package.json`
Reproduced issue locally and tested solution.
Both 0.10.0-dev.15 and 0.10.0 are problematic. When Evonet is updated with those DPP changes, DashJS will have to update at the same time to maintain compatibility.
Closes #26

fix: restrict to working dpp version

---

docs/platform/names/register.md
src/DashJS/SDK/Platform/methods/names/register.ts

`sdk.platform.names.register` has a `names` parameter. Before this change, it only accepted labels, and the only parent domain that could be used is `.dash`. This makes `names.register` more flexible, giving the same behavior as before, but also accepting names like `a.b.dash` or `a.b.other` if other TLDs are registered.
`sdk.platform.names.register` now splits the `name` parameter at the first period if it exists, and if not it falls back on the original behavior.
I altered the example node scripts to reference the un-compiled source files, then registered a variety of names successfully.

feat(names): Accept qualified names like evan.dash in names.register

---

package-lock.json
package.json
src/DashJS/SDK/Platform/Platform.ts
src/DashJS/SDK/Platform/methods/broadcastRecords.ts
src/DashJS/SDK/Platform/methods/contracts/broadcast.ts
src/DashJS/SDK/Platform/methods/contracts/create.ts
src/DashJS/SDK/Platform/methods/contracts/get.ts
src/DashJS/SDK/Platform/methods/documents/broadcast.ts
src/DashJS/SDK/Platform/methods/documents/create.ts
src/DashJS/SDK/Platform/methods/documents/get.ts
src/DashJS/SDK/Platform/methods/identities/get.ts
src/DashJS/SDK/Platform/methods/identities/register.ts
src/DashJS/SDK/Platform/methods/names/get.ts
src/DashJS/SDK/Platform/methods/names/register.ts
src/DashJS/SDK/SDK.ts
src/DashJS/SDK/StateTransitionBuilder/StateTransitionBuilder.ts
src/DashJS/SDK/StateTransitionBuilder/getTypeOfRecord.ts
src/DashJS/SDK/methods/isReady.ts
typings/dapi-client.d.ts

This PR is a direct follow-up on #30. 
Additionally to TypeScript typing documentation, Records get implemented as parent abstraction of dataContracts and documents (as initially proposed by @StEvUgnIn).
- docs: typing documentation (#30)
- refact: code cleanup (#30)
- refact: abstraction for ST creation/broadcasting (StateTransitionBuilder)

refact: Code cleanup & typing documentation

---

src/SDK/Client/Client.ts

Current seed IPs are out of date
Added seed IPs from redeployed evonet

fix: update default seed ips for re-deployed evonet

---

examples/node/register-identity.js
package.json
src/SDK/Client/Platform/methods/identities/register.ts

Make it possible to register an identity on Evonet 0.12.
Update dependencies and ID create ST signing
Ran register identity example.
**_This also requires an updated wallet-lib dependency which is not available on npm yet. Tested using the develop branch from GitHub_**

fix: DPP 0.12 identity create signing

---

CHANGELOG.md
package-lock.json
package.json
src/SDK/Client/Platform/methods/documents/broadcast.ts

I get the following error without this change when using `documents.broadcast`:
``` UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createStateTransition' of undefined```
`dpp.documents.createStateTransition` -> 
`dpp.document.createStateTransition`
Tested locally. Submitted several create documents successfully to contract `5wpZAEWndYcTeuwZpkmSa8s49cHXU5q2DhdibesxFSu8`

fix: changed dpp.documents (undefined) to dpp.document

---

README.md
docs/README.md
docs/examples/fetch-an-identity-from-its-name.md
docs/examples/generate-a-new-mnemonic.md
docs/examples/publishing-a-new-contract.md
docs/getting-started/quickstart.md
docs/getting-started/with-typescript.md
docs/wallet/accounts.md
examples/node/create-and-fund-wallet.js
examples/node/register-contract.js
examples/node/register-identity.js
examples/node/register-name.js
examples/node/sign-and-verify-messages.js
examples/web/usage.web.js
package.json
src/SDK/Client/Client.spec.ts
src/SDK/Client/Client.ts
tests/functional/index.js
tests/z_integrations/user-flow-1.js

Client options now accept `wallet` parameter of type `Wallet.Options` to introduce a namespace for wallet options. It should now be easier to configure wallet with `privateKey` instead of a `mnemonic` for example or do not initialize it if `wallet` param is not passed.
- Updated `Client` class constructor and `ClientOpts`
Existing tests have been updated and re-runned.

refactor: Client options now have `wallet` field to pre-configure wallet

---

.travis.yml

Currently PRs from external repos cannot successfully run tests because Travis prevents them from accessing the NPM token. 
This attempts to fix that by bypassing token access unless actually deploying (which should only happen from this repo).
This was first implemented on dashevo/dapi-grpc#61. Successfully running tests on this PR is an indication of success.
N/A

build: access npm token only when deploying

---

package-lock.json
package.json
tests/z_integrations/user-flow-1.js
webpack.base.config.js
webpack.config.js

Minified build for NodeJS fails with "u.DAPIClient is not a constructor" 
Disabled modification for NodeJS
With unit and integration tests
None

fix: minified build for NodeJS fails

---

package-lock.json
package.json
src/SDK/Client/Client.spec.ts
src/SDK/Client/Client.ts
src/SDK/Client/Platform/broadcastStateTransition.ts
src/SDK/Client/Platform/createAssetLockTransaction.ts
src/SDK/Client/Platform/methods/identities/register.ts
src/SDK/Client/Platform/methods/identities/topUp.ts
tests/functional/sdk.js

More than one call of `Client#identities.register` failed because SDK uses always the same private key.
- Get new unused private key for identity registration
- Sign asset lock transaction with a separate private key
- Update DPNS contract ID
- Use correct Identity private key for singing STs
- Enable ST validation before broadcasting
With unit and functional tests

fix: more than one identity registration failed

---

src/SDK/Client/Platform/createAssetLockTransaction.ts

Error with 'min relay fee not met' when registering/topping up an identity
Remove fee estimation from `createAssetLockTransaction` and fallback on the default estimation algorithm
Run existing tests
None

fix: wrong assetlock tx fee estimation

---

src/SDK/Client/Platform/createAssetLockTransaction.ts

Generate a one-time private key for identity registration and top-up sts instead of using one from the wallet
Made `createAssetLockTransaction` generate a new one-time private key every time a new asset lock transaction is created; Removed sending small amount of wallet funds to the address associated with the key to prevent it from getting reused.
Run the test
None

fix: generate one-time private key for the asset lock transaction

---

tsconfig.json

When working into the dash-sdk repository (for instance, when working with tsdoc), the tsconfig file would try to compile it (as we used `excludes` folder) which would fail the compilation. 
In order to fix that behavior and prevent further issues, and because we actually only compile contents of `/src`, we need to replace exclusions for inclusions. 
This is what this PR do. 
- tsconfig: specify inclusion instead of exclusion
Tested compilation & browsers unit test works as expected.
N/A

build(tsconfig): specify inclusions instead of exclusions

---

src/SDK/Client/Platform/methods/documents/get.spec.ts
src/SDK/Client/Platform/methods/documents/get.ts

For search for `Documents` to work we need to submit identifiers in `where` condition as `Buffers`
- Modified `douments.get` method
- Implemented tests
Unit tests.
None.

feat: convert string identifiers in `where` conditions

---

src/SDK/Client/Platform/methods/documents/get.spec.ts
src/SDK/Client/Platform/methods/documents/get.ts

In #145 we supposed to convert identifiers in where conditions from strings to buffers but system properties `$id` and `$ownerId` are not covered.
Convert system properties `$id` and `$ownerId` from strings to buffers in the `documents.get`'s `where` option. 
With unit test
None

fix: `$id` and `$ownerId` are not converted to identifiers

---

package-lock.json
package.json
src/SDK/Client/Platform/Platform.ts

To accommodate changes in Drive and DPP 
- Added `verifyInstanLock` method to `stateRepository` that returns `true`
Local node setup
None.

feat: add `verifyInstantLock` to state repository

---

.github/workflows/test_and_release.yml

Slow workflow runs can fill up the pipeline, making it necessary to manually cancel older runs. This PR adds an action to the workflow to cancel previous runs from the same branch with a different SHA.
Add `styfle/cancel-workflow-action` action
In CI

chore(ci): cancel previous workflow runs on push

---

.github/workflows/.env
package-lock.json
package.json
src/SDK/Client/Client.spec.ts
src/SDK/Client/Platform/broadcastStateTransition.ts
src/SDK/Client/Platform/methods/contracts/get.spec.ts
src/SDK/Client/Platform/methods/contracts/get.ts
src/SDK/Client/Platform/methods/identities/get.ts
src/errors/StateTransitionBroadcastError.ts

Provide detailed error information for the broadcast state transition method, including [DAPI](https://github.com/dashevo/dapi/pull/405)/[Drive](https://github.com/dashevo/js-drive/pull/564/files) common errors and [DPP consensus errors](https://github.com/dashevo/js-dpp/pull/341).
- Throw `StateTransitionBroadcastError` in case if local basic validation failed
- Add DAPI Client and DPP errors as a cause to `StateTransitionBroadcastError`
With tests
`StateTransitionBroadcastError#getData` is removed. Use `StateTransitionBroadcastError#getCause` to get additional details.

feat!: convenient broadcast errors

---

.github/workflows/.env
package-lock.json
package.json

There are several UTXO related bugs:
- Transaction is rejected: tx-txlock-conflict
- Not enough balance (0) to cover burn amount of 5
- utxosList must contain at least 1 utxo
Also, Due to a bug in `grpc-js` [explained here](https://github.com/grpc/grpc-node/issues/1652). A temporary solution is used to bypass this bug until a fix is merged into Node.js [explained here](https://github.com/nodejs/node/issues/38964#issuecomment-863917244)
Need to update DAPI Client to fix the bug with DAPI Client browser compatibility https://github.com/dashevo/js-dapi-client/pull/284
- Update DAPI Client
- Update Wallet
With CI
None

fix: UTXO selection doesn't work properly
